// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxOulcy-EbtCGtRak9zHsaRFZBYopNKBM',
    appId: '1:448331924833:web:67bf8e6b566277fe36f120',
    messagingSenderId: '448331924833',
    projectId: 'electrovice-app',
    authDomain: 'electrovice-app.firebaseapp.com',
    storageBucket: 'electrovice-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYHQ6V_tKRCqU-YDovpuKvEjFoTUeTQvo',
    appId: '1:448331924833:android:b4a47849c1c8cb0536f120',
    messagingSenderId: '448331924833',
    projectId: 'electrovice-app',
    storageBucket: 'electrovice-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDO_j2bsDC1pUosWbihFtF2SqqDRVrtWjQ',
    appId: '1:448331924833:ios:c4c7fb5a18e05e3036f120',
    messagingSenderId: '448331924833',
    projectId: 'electrovice-app',
    storageBucket: 'electrovice-app.firebasestorage.app',
    iosClientId: '448331924833-poh3lnakh6ptb20gp3u0o63gquc0lub0.apps.googleusercontent.com',
    iosBundleId: 'com.example.electrovice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDO_j2bsDC1pUosWbihFtF2SqqDRVrtWjQ',
    appId: '1:448331924833:ios:c4c7fb5a18e05e3036f120',
    messagingSenderId: '448331924833',
    projectId: 'electrovice-app',
    storageBucket: 'electrovice-app.firebasestorage.app',
    iosClientId: '448331924833-poh3lnakh6ptb20gp3u0o63gquc0lub0.apps.googleusercontent.com',
    iosBundleId: 'com.example.electrovice',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxOulcy-EbtCGtRak9zHsaRFZBYopNKBM',
    appId: '1:448331924833:web:433fcebcb2f2071136f120',
    messagingSenderId: '448331924833',
    projectId: 'electrovice-app',
    authDomain: 'electrovice-app.firebaseapp.com',
    storageBucket: 'electrovice-app.firebasestorage.app',
  );
}
